### ISSUE TITLE
Monorepo support?

### ISSUE THREAD

**Issue by Nfinished** [bmish/eslint-doc-generator#439]
Sorry if this is covered in the readme, nothing seemed relevant.

I've got a monrepo using Yarn 2 workspaces and when running `lint` (lint will run eslint-doc-generator --check in my eslint package) from the project directory it seems like eslint-doc-generator can't find its package's package.json. Is there a flag I can pass for this case?

```sh
@nfinished/eslint-plugin:lint: Could not find package.json of ESLint plugin.
@nfinished/eslint-plugin:lint: ERROR: "update:eslint-docs -- --check" exited with 1.
@nfinished/eslint-plugin:lint: ERROR: "lint:eslint-docs" exited with 1.
@nfinished/eslint-plugin:lint: ERROR: command finished with error: command (packages/eslint-plugin) yarn run lint exited (1)
```

**Comment by bmish** [comment]
eslint-doc-generator shouldn't need to be specifically aware of the presence of a monorepo. It's typically just installed in the eslint plugin package, and by default, it will assume package.json exists in the directory it's run from. 

But there's also a positional argument if you need to run it from somewhere else:

> The CLI has an optional path argument if you need to point the CLI to an ESLint plugin directory that isn't just the current directory.

```sh
eslint-doc-generator path/to/plugin
```

If that doesn't help, can you tell me more about your monorepo setup? I can't really tell what your files and scripts look like.

**Comment by Nfinished** [comment]
Ah nope, that solves my case. I just totally skimmed over that line in the docs because it was right before the table with the rest of the args. Thank you!

**Comment by bmish** [comment]
Great! I can improve the doc a bit: https://github.com/bmish/eslint-doc-generator/pull/441

**Comment by Nfinished** [comment]
Thank you! I appreciate it. Do you have any thoughts on how to approach running the command from different locations?

ex in a yarn2 monorepo running `lint` from the package itself vs running `lint` from the project root, which _should_ run lint in ever registered package directory but in the case of eslint-doc-generator seems to run the command from the root directory.

**Comment by bmish** [comment]
So I consider it best practice for every package in a monorepo to define its own lint (and test) scripts, as each package knows best how to lint and test itself, and so that individual packages don't have to have awareness of the surrounding workspace. An example of a package's lint scripts is shown in the [Setup](https://github.com/bmish/eslint-doc-generator#setup) section of the README. 

As far as how to run these scripts, use something like `yarn workspace lint` or `lerna run lint` to ensure the command is run in each package.

Now if that running it isn't working from outside the package, then there might be an actual bug in our code to determine the package root:

https://github.com/bmish/eslint-doc-generator/blob/6fed2f843f9366cd8d767fac1ee17cf4af580f29/lib/package-json.ts#L17-L19

**Comment by Nfinished** [comment]
Thanks, I'm thinking this might've been an issue with yarn2 workspaces and npm-run-all, which is how the --check is run when a project is created with eslint-plugin's yeoman generator. Switched to concurrently and it's working as expected.
