### ISSUE TITLE
Docs get regenerated

### ISSUE THREAD

**Issue by anubra266** [bmish/eslint-doc-generator#510]
https://github.com/bmish/eslint-doc-generator/assets/30869823/a1809446-789c-4d22-b234-93229fc247fe

**Comment by bmish** [comment]
Can you copy and paste the rule doc here or link to it? This would normally only happen if `<!-- end auto-generated rule header -->` is missing.

**Comment by anubra266** [comment]
@bmish I no longer have this code locally, but in the video I pasted, that line exists

**Comment by bmish** [comment]
Yes it does look correct in the video. The only thing that looks weird to me in the video is that `-->` looks like a single character which break it, but that might just be the font your editor is using.

I think I'll need a code sample in order to reproduce this. So until then, I'll close this issue. If it happens to you again, let me know. Thanks for reporting.

**Comment by bmish** [comment]
I think this might be a Windows-specific issue and I'm working on a potential fix in #524.
