### ISSUE TITLE
Add an emoji for 'recommended-type-checked'

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [bmish/eslint-doc-generator#517]
Coming over from https://github.com/eslint-community/eslint-plugin-eslint-plugin/pull/433#discussion_r1478577673:

> I don't love that this doesn't have its own emoji 😞 is there some standard practice that can be done?
> Yes I would just give it a different color checkmark like [☑️](https://emojipedia.org/check-box-with-check) in `.eslint-doc-generatorrc.js`.

Would adding `recommended-type-checked: ☑️` to the list of built-in rule config emojis make be reasonable? I don't know of configs other than typescript-eslint that use that (pending https://github.com/eslint-community/eslint-plugin-eslint-plugin/pull/433), but it strikes me as a reasonable preset.

https://github.com/bmish/eslint-doc-generator/blob/e669f765c7095c575e6bf8d98588b0254d37d7ee/lib/emojis.ts#L11-L17

**Comment by bmish** [comment]
I'm open to this since this config name `recommended-type-checked` seems like a common or recommended convention for type-aware rules, as seen here: https://typescript-eslint.io/linting/typed-linting/

My original idea behind using ☑️ for it is that this black/white checkmark is a variation of the green checkmark ✅ used for `recommended`, the way that `recommended-type-checked` is a variation/extension of the `recommended` config. There's also [✔️](https://emojipedia.org/check-mark) but that is a bit less consistent with the styling.

There's also ⌨️ which could make sense as we're using it for other TypeScript-related configs, but it doesn't have the benefit that ☑️ does of implying a relation to the recommended config.

So it seems we can start with ☑️.
