### ISSUE TITLE
Add emoji for `type-checked` config

### ISSUE THREAD

**Issue by bmish** [bmish/eslint-doc-generator#519]
I'm thinking we can add our current TypeScript-related emoji of ⌨️ to the config name `type-checked` going along with some of the existing TypeScript/type-related config names we have. We wouldn't use ☑️ for this since it's not necessarily related to the recommended config.

Follow-up to:
* #517

Related discussion:
* https://github.com/eslint-community/eslint-plugin-eslint-plugin/issues/445

CC: @JoshuaKGoldberg

**Comment by ljharb** [comment]
I’m confused; what does “type-checked” indicate?

**Comment by bmish** [comment]
It's just one possible name that plugins might use for configs containing type-aware rules, which would usually have `meta.docs.requiresTypeChecking` enabled. Discussion in https://github.com/eslint-community/eslint-plugin-eslint-plugin/issues/445.

Note that plugins don't need to use this name or config, as the idea is just to provide emojis for a variety of common or possible config names.

**Comment by ljharb** [comment]
that seems like a really weird name since it appears to describe the config itself rather than the code it’s linting - nobody should care if the plugin code is type-checked or not.

**Comment by ljharb** [comment]
`type-aware` seems like a good name for that.

**Comment by bmish** [comment]
`type-aware` sounds nice and concise. I'll defer to @JoshuaKGoldberg on the official typescript-eslint conventions or recommendations but will aim to support any variation here.

**Comment by JoshuaKGoldberg** [comment]
Oh shoot I missed this till now - `type-aware` is a really interesting name. cc @bradzacher, I actually like it more than `type-checked` for the reasons stated.

The problem is, we _just_ did a set of config renames like `recommended-requiring-type-checking` to `recommended-type-checked` (https://github.com/typescript-eslint/typescript-eslint/discussions/6019) last year. And then we released flat config support over the last couple of months.

So... as much as I prefer "aware", I'm not sure that it can be more than just a nice terminology alias for a while in typescript-eslint itself 😞. Which makes it hard to recommend other configs use it.
